<template>
    <div
        class="rounded-lg min-w-sm border overflow-hidden flex flex-col justify-between bg-bg-card w-full transition-all duration-300"
        :class="[
            isGeneratingWithAI ? 'glow-border-animation border-accent' : 'border-border',
        ]">
        <!-- Header -->
        <div class="px-3 pt-3">
            <div class="flex justify-between items-start ">
                <div>
                    <h3 class="text-lg font-semibold text-text-primary">{{ title }}</h3>
                    <p class="text-xs text-text-secondary ">{{ subtitle }}</p>
                </div>
                <span class="text-xs border rounded-full px-2 py-0.5" :class="getColor(status)">
                    {{ status }}
                </span>

            </div>
            <!-- Progress -->
            <div class="my-2 pb-3">
                <div class="flex justify-between text-sm text-text-secondary mb-1">
                    <span class="font-medium">
                        {{ isGeneratingWithAI ? 'Creating Tasks with AI...' : 'Progress' }}
                    </span>
                    <span>{{ Math.round(liveProgress) }}%</span>
                </div>

                <ProgressBar class='mt-2' :progress="liveProgress" fillColor="bg-accent" :indeterminate="isGeneratingWithAI" />

                <!-- Task breakdown (mock UI for now) -->
                <div v-if="showTaskBreakdown" class="mt-2 text-xs text-text-secondary flex items-center gap-2">
                    <span class="font-medium text-text-primary">{{ completedTasks }}/{{ totalTasks }}</span>
                    <span>tasks completed</span>
                    <span v-if="inProgressTasks > 0" class="ml-auto text-blue-400">
                        {{ inProgressTasks }} in progress
                    </span>
                </div>
            </div>
        </div>


        <!-- Footer -->
        <div class="flex justify-between items-center  bg-bg-body p-3  ">
            <!-- Avatars -->
            <div class="flex -space-x-2">
                <img v-for="(avatar, index) in visibleAvatars" :key="index" :src="avatar"
                    class="w-6 h-6 rounded-full border-2 border-border object-cover shadow" />
                <div v-if="extraCount > 0"
                    class="w-6 h-6 rounded-full border-2 border-border bg-bg-card text-[11px] font-semibold flex items-center justify-center text-text-secondary  shadow">
                    +{{ extraCount }}
                </div>
            </div>

            <!-- Date -->
            <div class="flex items-center gap-1 text-sm text-text-secondary ">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M8 7V3M16 7V3M4 11h16M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                {{ date }}
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import ProgressBar from '../ui/ProgressBar.vue';
import { useIndeterminateProgress } from '../../utilities/IndeterminateProgress';

// TODO: Add this interface when API is ready
// interface TaskData {
//   totalTasks: number
//   completedTasks: number
//   inProgressTasks: number
//   pendingTasks: number
// }

const props = defineProps<{
    title: string
    subtitle: string
    status: any
    progress: number
    avatars: string[]
    maxVisible?: number
    date: string
    loading?: any
    isManualMode?: boolean  // true if workspace created manually, false if AI-generated
    // taskData?: TaskData  // TODO: Uncomment when API is available
}>()

// Determine if this card is actively being generated by AI
const isGeneratingWithAI = computed(() =>
    !props.isManualMode && props.status === 'in_progress' && props.progress < 100
)

// liveProgress: auto-advances when loading = true, else shows the real progress prop
const indeterminate = useIndeterminateProgress(() => isGeneratingWithAI.value)
const liveProgress = computed(() => isGeneratingWithAI.value ? indeterminate.value : props.progress)

// Show task breakdown after AI completes or for manual workspaces
const showTaskBreakdown = computed(() =>
    props.isManualMode || (!isGeneratingWithAI.value && props.progress > 0)
)

// ========================================
// TODO: API Integration Point
// ========================================
// Replace mock calculations with real API data
// Expected API response shape:
// {
//   totalTasks: number
//   completedTasks: number
//   inProgressTasks: number
//   pendingTasks: number
// }
// ========================================

// Mock task calculations based on progress (TODO: Replace with API data)
const totalTasks = computed(() => 10) // Mock value - replace with props.taskData?.totalTasks
const completedTasks = computed(() => Math.round((props.progress / 100) * totalTasks.value)) // Replace with props.taskData?.completedTasks
const inProgressTasks = computed(() => {
    if (props.status === 'in_progress' && !isGeneratingWithAI.value) {
        return Math.max(0, Math.min(3, totalTasks.value - completedTasks.value)) // Replace with props.taskData?.inProgressTasks
    }
    return 0
})

const maxVisible = props.maxVisible ?? 2



const visibleAvatars = computed(() => props.avatars.slice(0, maxVisible))
const extraCount = computed(() =>
    props.avatars.length > maxVisible ? props.avatars.length - maxVisible : 0
)

const getColor = (status: string) => {
    if (isGeneratingWithAI.value) {
        return 'bg-accent/20 border-accent text-accent animate-pulse'
    }
    switch (status) {
        case 'completed': return 'bg-green-400/40 border-green-400 text-green-400'
        case 'failed': return 'bg-red-400/40 border-red-400 text-red-400'
        case 'in_progress': return 'bg-blue-400/20 border-blue-400 text-blue-400'
        case 'pending': return 'bg-amber-400/20 border-amber-400 text-amber-400'
        default: return 'bg-gray-400/20 border-gray-400 text-gray-400'
    }
}
</script>

<style scoped>
@keyframes glow-pulse {
    0%, 100% {
        box-shadow: 0 0 8px rgba(var(--accent-rgb, 59, 130, 246), 0.4),
                    0 0 16px rgba(var(--accent-rgb, 59, 130, 246), 0.2);
    }
    50% {
        box-shadow: 0 0 16px rgba(var(--accent-rgb, 59, 130, 246), 0.6),
                    0 0 32px rgba(var(--accent-rgb, 59, 130, 246), 0.3);
    }
}

.glow-border-animation {
    animation: glow-pulse 2s ease-in-out infinite;
}

@keyframes shimmer {
    0% {
        background-position: -200% 0;
    }
    100% {
        background-position: 200% 0;
    }
}

:deep(.shimmer-effect) {
    background: linear-gradient(
        90deg,
        currentColor 0%,
        rgba(255, 255, 255, 0.8) 50%,
        currentColor 100%
    );
    background-size: 200% 100%;
    animation: shimmer 2s linear infinite;
}
</style>